module.exports = [
    {
        name: 'test',
        type: 'postgres',
        host: `${process.env.TEST_HOST}`,
        port: `${process.env.TEST_PORT}`,
        username: `${process.env.TEST_USERNAME}`,
        password: `${process.env.TEST_PASSWORD}`,
        database: `${process.env.TEST_DATABASE}`,
        dropSchema: true,
        logging: false,
        synchroize: true,
        migrationsRun: true,
        entities: ['src/entity/**/*.ts'],
        migrations: ['src/migration/**/*.ts'],
        subscribers: ['src/subscriber/**/*.ts'],
        cli: {
            entitiesDir: 'src/entity',
            migrationsDir: 'src/migration',
            subscribersDir: 'src/subscriber',
        },
    },
    {
        name: 'development',
        type: 'postgres',
        host: `${process.env.DEVELOPMENT_HOST}`,
        port: `${process.env.DEVELOPMENT_PORT}`,
        username: `${process.env.DEVELOPMENT_USERNAME}`,
        password: `${process.env.DEVELOPMENT_PASSWORD}`,
        database: `${process.env.DEVELOPMENT_DATABASE}`,
        synchronize: false,
        logging: false,
        entities: ['src/entity/**/*.ts'],
        migrations: ['src/migration/**/*.ts'],
        subscribers: ['src/subscriber/**/*.ts'],
        cli: {
            entitiesDir: 'src/entity',
            migrationsDir: 'src/migration',
            subscribersDir: 'src/subscriber',
        },
    },
    {
        name: 'default',
        type: 'postgres',
        host: `${process.env.DEFAULT_HOST}`,
        port: `${process.env.DEFAULT_PORT}`,
        username: `${process.env.DEFAULT_USERNAME}`,
        password: `${process.env.DEFAULT_PASSWORD}`,
        database: `${process.env.DEFAULT_DATABASE}`,
        synchronize: false,
        logging: false,
        entities: ['src/entity/**/*.ts'],
        migrations: ['src/migration/**/*.ts'],
        subscribers: ['src/subscriber/**/*.ts'],
        cli: {
            entitiesDir: 'src/entity',
            migrationsDir: 'src/migration',
            subscribersDir: 'src/subscriber',
        },
    },
];
